#!/bin/bash

export INGEST_API=http://localhost:8080
export INGEST_S3_BUCKET=org-hca-data-archive-upload-dev
export INGEST_S3_REGION=us-east-1
export RABBIT_HOST=localhost
export RABBIT_PORT=5672
export AWS_ACCESS_KEY_ID=
export AWS_ACCESS_KEY_SECRET=
export ENA_FTP_HOST=webin.ebi.ac.uk
export ENA_FTP_DIR=dev
export ENA_WEBIN_USERNAME=Webin-46220
export ENA_WEBIN_PASSWORD=
export ARCHIVER_DATA_DIR=/data
